name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Infracost breakdown
        uses: infracost/actions@v2
        with:
          path: ./terraform/tfplan
          api_key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Post Infracost Comment
        if: github.event_name == 'pull_request'
        run: infracost comment github --path infracost --repo ${{ github.repository }} --pull-request ${{ github.event.pull_request.number }}

